### ISSUE TITLE
Copy errors with cartoflow

### ISSUE THREAD

**Issue by smoorsh** [ZealousGeneticist/cartoflow#1]
Here is the error when I ran cartoflow:

[smoorsh@node1862 cartoflow]$ bash cartoflow.sh -i cinnamon_met_CAS.tsv 
Cloning into 'cartogene'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 132 (delta 15), reused 20 (delta 8), pack-reused 104
Receiving objects: 100% (132/132), 52.53 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (74/74), done.
Cloning into 'linkcomm'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 181 (delta 0), reused 3 (delta 0), pack-reused 174
Receiving objects: 100% (181/181), 78.95 KiB | 2.32 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Cloning into 'genebridge'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 42 (delta 25), reused 26 (delta 12), pack-reused 0
Receiving objects: 100% (42/42), 24.77 KiB | 6.19 MiB/s, done.
Resolving deltas: 100% (25/25), done.

If git wasn't 'found', then you may have to run this:
sudo apt install git

Cartogene Phase...
requests is already installed.
pandas is already installed.
str2bool is already installed.

Begining Comparative Toxicogenomics Database (CTD) chemical-gene interaction Batch Query...
Done with chemical to gene interactions! Have a great rest of your research, dude! :)

Beginning to grab all interaction data from IntAct on all genes in CTD datatable...
The number of elements in total: 771
The number of files shall be: 1
Omniscience prepped. Beginning to write file: 
 1 of 1
The server will take about 0:00:01.071064 to process each file.

Saving...
Status:  200
File 1 saved.

Omniscience complete. 
 1 file(s) have been blessed upon you.
The sciences shall voyage far from our island of ignorance into the midst of black seas of infinity.

Oh yeah, reductionism time...
 Please wait...
faceted_intact_results_0_PPI.json is done being reduced!
Reduced to atoms... or at least: 
 7.86 kB
Linkcomm Phase...
# loading network from edgelist...
/home/smoorsh/ondemand/data/2024_01_19_cartoflow/cartoflow/linkcomm/python/link_clustering.py:210: DeprecationWarning: 'U' mode is deprecated
  for line in open(filename, 'U'):
clustering...
computing similarities...
# D_max = 0.000906
# S_max = 0.046154
Genebridge Phase...
networkx is already installed.
matplotlib is already installed.
numpy is already installed.
pandas is already installed.
scipy is already installed.
pyvis is already installed.
str2bool is already installed.
requests is already installed.

Found matching file: faceted_inact_node_network_maxS0.046154_maxD0.000906.edge2comm.txt
Found matching file: faceted_inact_node_network_maxS0.046154_maxD0.000906.comm2nodes.txt
Nodes: 420
Edges: 460

Node Data chugging time.
Traceback (most recent call last):
  File "/home/smoorsh/ondemand/data/2024_01_19_cartoflow/cartoflow/genebridge/genebridge.py", line 158, in <module>
    E_C = nx.eigenvector_centrality_numpy(G) #dictionary
  File "/software/spackages/linux-rocky8-x86_64/gcc-9.5.0/anaconda3-2022.05-zyrazrj6uvrtukupqzhaslr63w7hj6in/lib/python3.9/site-packages/networkx/algorithms/centrality/eigenvector.py", line 223, in eigenvector_centrality_numpy
    M = nx.to_scipy_sparse_array(G, nodelist=list(G), weight=weight, dtype=float)
  File "/software/spackages/linux-rocky8-x86_64/gcc-9.5.0/anaconda3-2022.05-zyrazrj6uvrtukupqzhaslr63w7hj6in/lib/python3.9/site-packages/networkx/convert_matrix.py", line 921, in to_scipy_sparse_array
    A = sp.sparse.coo_array((d, (r, c)), shape=(nlen, nlen), dtype=dtype)
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'
cp: cannot stat 'community': No such file or directory
cp: cannot stat 'Pyvis_Graph.html': No such file or directory
cp: cannot stat 'commMetrics.tsv': No such file or directory
cp: cannot stat 'nodeMetrics.tsv': No such file or directory
Workflow complete!

**Comment by ZealousGeneticist** [comment]
Hey @smoorsh ! Sorry for the delay, but I think this last update should have fixed all these issues! Please reinstall the newest version of CartoFlow and tell me if it works or not. If it doesn't work, please post the new errors here!
