### ISSUE TITLE
Cartoflow is not working on my input chemical file on palmetto

### ISSUE THREAD

**Issue by madmont02** [ZealousGeneticist/cartoflow#3]
Here is my chemical list:
Gamma-aminobutyric acid Betaxanthin
Betaine
Betanin
Indicaxanthin
Isobetanin
Isoleucine Betaxanthin
leucine Betaxanthin
Miraxanthin V
Muscaaurin VII
Phenylalanine Betaxanthin
Serine Betaxanthin 
Tryptophan Betaxanthin
Valine Betaxanthin
Vulgaxanthin I 
Vulgaxanthin IV

Here are the errors I'm getting:
[maddenm@login002 cartoflow]$ bash cartoflow.sh -i golden_beets
fatal: destination path 'cartogene' already exists and is not an empty directory.
fatal: destination path 'linkcomm' already exists and is not an empty directory.
fatal: destination path 'genebridge' already exists and is not an empty directory.
If git wasn't 'found', then you may have to run this:
sudo apt install git
Cartogene Phase...
Collecting certifi==2023.11.17 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-202
3.11.17-py3-none-any.whl
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement charset-normalizer==3.3.2 (from -r requirements.txt (line 2)) (from version
s: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3
.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0
.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)
No matching distribution found for charset-normalizer==3.3.2 (from -r requirements.txt (line 2))
Traceback (most recent call last):
  File "cartogene_standalone.py", line 36, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Linkcomm Phase...
cp: cannot stat 'faceted_inact_node_network.tsv': No such file or directory
# loading network from edgelist...
Traceback (most recent call last):
  File "python/link_clustering.py", line 358, in <module>
    adj,edges        = read_edgelist_unweighted(args[0], delimiter=delimiter)
  File "python/link_clustering.py", line 210, in read_edgelist_unweighted
    for line in open(filename, 'U'):
FileNotFoundError: [Errno 2] No such file or directory: 'faceted_inact_node_network.tsv'
Genebridge Phase...
cp: missing destination file operand after '../genebridge'
Try 'cp --help' for more information.
cp: missing destination file operand after '../genebridge'
Try 'cp --help' for more information.
cp: cannot stat 'interactionsCTD_chemical-protein.tsv': No such file or directory
Collecting asttokens==2.4.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2
.4.1-py2.py3-none-any.whl
Collecting certifi==2023.11.17 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-202
3.11.17-py3-none-any.whl
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement charset-normalizer==3.3.2 (from -r requirements.txt (line 3)) (from version
s: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3
.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0
.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)
No matching distribution found for charset-normalizer==3.3.2 (from -r requirements.txt (line 3))
Traceback (most recent call last):
  File "genebridge.py", line 33, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
cp: cannot stat 'community': No such file or directory
cp: cannot stat 'Pyvis_Graph.html': No such file or directory
cp: cannot stat 'commMetrics.tsv': No such file or directory
cp: cannot stat 'nodeMetrics.tsv': No such file or directory
cp: missing destination file operand after '../edge2comm.txt'
Try 'cp --help' for more information.
Workflow complete!

**Comment by ZealousGeneticist** [comment]
Hi! It seems that a recent update with cartogene & genebridge may have led to a few errors in installing the packages it needs from a requirement list, which is leading to them not being installed and thus the program being unable to run. A patch is being implemented soon!

**Comment by ZealousGeneticist** [comment]
Hello! An update was just applied that should fix it so even if something like Palmetto doesn't have access to the specific version that is requested in 'requirements.txt', it will attempt to get the closest version too that one. That should fix it for supercomputers that only have access to specific package versions for safety reasons! Hope this helps @madmont02 ! Tell me if it works and I will close this issue.

**Comment by madmont02** [comment]
I am still receiving the same error.

**Comment by ZealousGeneticist** [comment]
Hey @madmont02 . Sorry for the delay, but I think this last update should have fixed all these issues! Please reinstall the newest version of CartoFlow and tell me if it works or not. If it doesn't work, please post the new errors here!

**Comment by madmont02** [comment]
I tried reinstalling the newest version and this was the error I received:
[maddenm@login002 cartoflow]$ bash cartoflow.sh -i beets_chemicals
Cloning into 'cartogene'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 140 (delta 19), reused 24 (delta 8), pack-reused 104
Receiving objects: 100% (140/140), 53.98 KiB | 1.86 MiB/s, done.
Resolving deltas: 100% (78/78), done.
Cloning into 'linkcomm-U'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 83 (delta 2), reused 2 (delta 0), pack-reused 72
Receiving objects: 100% (83/83), 51.84 KiB | 1.79 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Cloning into 'genebridge'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 52 (delta 30), reused 34 (delta 15), pack-reused 0
Receiving objects: 100% (52/52), 27.44 KiB | 1.61 MiB/s, done.
Resolving deltas: 100% (30/30), done.

If git wasn't 'found', then you may have to run this:
sudo apt install git

Cartogene Phase...
cp: cannot stat 'beets_chemicals': No such file or directory
Collecting certifi<=2023.11.17 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-2023.11.17-py3-none-any.whl
Collecting charset-normalizer<=3.3.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/68/2b/02e9d6a98ddb73fa238d559a9edcc30b247b8dc4ee848b6184c936e99dc0/charset_normalizer-3.0.1-py3-none-any.whl
Requirement already satisfied: idna<=3.6 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Collecting numpy<=1.26.3 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting pandas<=2.1.4 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/c3/e2/00cacecafbab071c787019f00ad84ca3185952f6bb9bca9550ed83870d4d/pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil<=2.8.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Collecting pytz<=2023.3.post1 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl
Requirement already satisfied: requests<=2.31.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: setuptools<=68.2.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: six<=1.16.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Collecting str2bool<=1.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/fc/8c/42e61df3b86bb675b719877283da915d3db93fb0d1820fc7bf2a9153f739/str2bool-1.1.zip
Collecting tzdata<=2023.4 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/a3/fb/52b62131e21b24ee297e4e95ed41eba29647dad0e0051a92bb66b43c70ff/tzdata-2023.4-py2.py3-none-any.whl
Requirement already satisfied: urllib3<=2.1.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 13))
Collecting wheel<=0.41.2 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests<=2.31.0->-r requirements.txt (line 8))
Installing collected packages: certifi, charset-normalizer, numpy, pytz, pandas, str2bool, tzdata, wheel
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'
Traceback (most recent call last):
  File "cartogene_standalone.py", line 36, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
LinkComm-U Phase...
cp: cannot stat 'faceted_inact_node_network.tsv': No such file or directory
# loading network from edgelist...
Traceback (most recent call last):
  File "python/link_clustering.py", line 358, in <module>
    adj,edges        = read_edgelist_unweighted(args[0], delimiter=delimiter)
  File "python/link_clustering.py", line 210, in read_edgelist_unweighted
Resolving deltas: 100% (30/30), done.
    for line in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'faceted_inact_node_network.tsv'
Genebridge Phase...
cp: missing destination file operand after '../genebridge'
Try 'cp --help' for more information.
cp: missing destination file operand after '../genebridge'
Try 'cp --help' for more information.
cp: cannot stat 'interactionsCTD_chemical-protein.tsv': No such file or directory
cp: cannot stat 'interactionsCTD_chemical-protein.tsv': No such file or directory
Collecting asttokens<=2.4.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233
b24a/asttokens-2.4.1-py2.py3-none-any.whl
Collecting certifi<=2023.11.17 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe
4f42/certifi-2023.11.17-py3-none-any.whl
Collecting charset-normalizer<=3.3.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/68/2b/02e9d6a98ddb73fa238d559a9edcc30b247b8dc4ee848b6184c936e9
9dc0/charset_normalizer-3.0.1-py3-none-any.whl
Collecting contourpy<=1.2.0 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement contourpy<=1.2.0 (from -r requirements.txt (line 4)) (from 
versions: )
No matching distribution found for contourpy<=1.2.0 (from -r requirements.txt (line 4))
Traceback (most recent call last):
  File "genebridge.py", line 33, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
cp: cannot stat 'community': No such file or directory
cp: cannot stat 'Pyvis_Graph.html': No such file or directory
cp: cannot stat 'commMetrics.tsv': No such file or directory
cp: cannot stat 'nodeMetrics.tsv': No such file or directory
cp: missing destination file operand after '../edge2comm.txt'
Try 'cp --help' for more information.
Workflow complete!

**Comment by madmont02** [comment]
My chemical list was the same as before: 
Gamma-aminobutyric acid Betaxanthin
Betaine
Betanin
Indicaxanthin
Isobetanin
Isoleucine Betaxanthin
leucine Betaxanthin
Miraxanthin V
Muscaaurin VII
Phenylalanine Betaxanthin
Serine Betaxanthin
Tryptophan Betaxanthin
Valine Betaxanthin
Vulgaxanthin I
Vulgaxanthin IV

**Comment by ZealousGeneticist** [comment]
Hey @madmont02 , are you sure your chemical file is only listed as 'beets_chemicals'?
When you ran:
 [maddenm@login002 cartoflow]$ bash cartoflow.sh -i beets_chemicals
 It seems the program couldn't find that file. you may have named it beets_chemicals.tsv or beets_chemicals.txt or soemthing like that, but it needs the full input file name including the extension at the end. That seems to be the major issue there.

**Comment by madmont02** [comment]
yes i had it saved as that, i tried making another file and making it a .txt and tried that way but received the same error:
[maddenm@login002 cartoflow]$ bash cartoflow.sh -i beets_chem.txt
Cloning into 'cartogene'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 140 (delta 19), reused 24 (delta 8), pack-reused 104
Receiving objects: 100% (140/140), 53.98 KiB | 1.80 MiB/s, done.
Resolving deltas: 100% (78/78), done.
Cloning into 'linkcomm-U'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 83 (delta 2), reused 2 (delta 0), pack-reused 72
Receiving objects: 100% (83/83), 51.84 KiB | 1.62 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Cloning into 'genebridge'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 52 (delta 30), reused 34 (delta 15), pack-reused 0
Receiving objects: 100% (52/52), 27.44 KiB | 1.61 MiB/s, done.
Resolving deltas: 100% (30/30), done.

If git wasn't 'found', then you may have to run this:
sudo apt install git

Cartogene Phase...
Collecting certifi<=2023.11.17 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-2023.11.17-py3-none-any.whl
Collecting charset-normalizer<=3.3.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/68/2b/02e9d6a98ddb73fa238d559a9edcc30b247b8dc4ee848b6184c936e99dc0/charset_normalizer-3.0.1-py3-none-any.whl
Requirement already satisfied: idna<=3.6 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Collecting numpy<=1.26.3 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting pandas<=2.1.4 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/c3/e2/00cacecafbab071c787019f00ad84ca3185952f6bb9bca9550ed83870d4d/pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil<=2.8.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Collecting pytz<=2023.3.post1 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl
Requirement already satisfied: requests<=2.31.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: setuptools<=68.2.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: six<=1.16.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Collecting str2bool<=1.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/fc/8c/42e61df3b86bb675b719877283da915d3db93fb0d1820fc7bf2a9153f739/str2bool-1.1.zip
Collecting tzdata<=2023.4 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/a3/fb/52b62131e21b24ee297e4e95ed41eba29647dad0e0051a92bb66b43c70ff/tzdata-2023.4-py2.py3-none-any.whl
Requirement already satisfied: urllib3<=2.1.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 13))
Collecting wheel<=0.41.2 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests<=2.31.0->-r requirements.txt (line 8))
Installing collected packages: certifi, charset-normalizer, numpy, pytz, pandas, str2bool, tzdata, wheel
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'
Traceback (most recent call last):
  File "cartogene_standalone.py", line 36, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
LinkComm-U Phase...
cp: cannot stat 'faceted_inact_node_network.tsv': No such file or directory
# loading network from edgelist...
Traceback (most recent call last):
  File "python/link_clustering.py", line 358, in <module>
    adj,edges        = read_edgelist_unweighted(args[0], delimiter=delimiter)
  File "python/link_clustering.py", line 210, in read_edgelist_unweighted
    for line in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'faceted_inact_node_network.tsv'
Genebridge Phase...
cp: missing destination file operand after '../genebridge'
Try 'cp --help' for more information.
cp: missing destination file operand after '../genebridge'
Try 'cp --help' for more information.
cp: cannot stat 'interactionsCTD_chemical-protein.tsv': No such file or directory
cp: cannot stat 'interactionsCTD_chemical-protein.tsv': No such file or directory
Collecting asttokens<=2.4.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2.4.1-py2.py3-none-any.whl
Collecting certifi<=2023.11.17 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/64/62/428ef076be88fa93716b576e4a01f919d25968913e817077a386fcbe4f42/certifi-2023.11.17-py3-none-any.whl
Collecting charset-normalizer<=3.3.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/68/2b/02e9d6a98ddb73fa238d559a9edcc30b247b8dc4ee848b6184c936e99dc0/charset_normalizer-3.0.1-py3-none-any.whl
Collecting contourpy<=1.2.0 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement contourpy<=1.2.0 (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for contourpy<=1.2.0 (from -r requirements.txt (line 4))


Traceback (most recent call last):
  File "genebridge.py", line 33, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
cp: cannot stat 'community': No such file or directory
cp: cannot stat 'Pyvis_Graph.html': No such file or directory
cp: cannot stat 'commMetrics.tsv': No such file or directory
cp: cannot stat 'nodeMetrics.tsv': No such file or directory
cp: missing destination file operand after '../edge2comm.txt'
Try 'cp --help' for more information.
Workflow complete!

**Comment by ZealousGeneticist** [comment]
@madmont02 **So, that actually not the same error!** The last error was resolved it seems and could find beets_chem.txt .
However, it seems that this caused your error this time:

Installing collected packages: certifi, charset-normalizer, numpy, pytz, pandas, str2bool, tzdata, wheel
Exception:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
strip_file_prefix=options.strip_file_prefix,
File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
**kwargs
File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
strip_file_prefix=strip_file_prefix
File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
strip_file_prefix=strip_file_prefix,
File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
clobber(source, lib_dir, True)
File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
ensure_dir(dest) # common for the 'include' path
File "/usr/lib/python3.6/site-packages/pip/utils/init.py", line 83, in ensure_dir
os.makedirs(path)
File "/usr/lib64/python3.6/os.py", line 210, in makedirs
makedirs(head, mode, exist_ok)
File "/usr/lib64/python3.6/os.py", line 220, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'

The error message you provided indicates that the issue is occurring during the installation of Python packages using pip. The PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6' is indicates that the process does not have the necessary permissions to write to the /usr/local/lib/python3.6 directory. This error typically happens when trying to install packages globally without sufficient privileges. 

You could try running these commands while you are in the cartogene AND genebridge directory:
sudo pip install -r requirments.txt
OR
pip install -r --user requirments.txt

If neither of these work, try to ask someone you know of who can give you rewrite access on the machine or, if you still do not have permission to download the packages required like pandas to for the program to run, then you would have to run it on a machine you **DO** have those permissions on. This could include a laptop, pc, or a virtual machine that you have access to.
